### ISSUE TITLE
Idea: Deprecate validate_completely

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#101]
Currently, the [`Validate`](https://docs.rs/gltf-json/0.9.2/gltf_json/validation/trait.Validate.html) trait performs basic validation to ensure the crate can function safely. This includes checking bounds of indices and ensuring all required data is available ahead of time. These 'basic' checks are performed by `validate_minimally`.

The second function, `validate_completely`, was intended to validate 'completely' against the 2.0 specification. There hasn't been much progress on this and there are concerns with the API since `validate_completely` doesn't include all the checks from `validate_minimally`. Hence, I suggest we deprecate this function and remove it in 1.0.

#### Suggested alternatives

1. Make 'complete' validation an opt-in feature for `gltf-json` (e.g. `#[cfg(feature = "extra-validation")]`).
2. Always perform 'complete' validation. This would be achieved by merging all existing `validate_completely` checks into `validate_minimally`.
3. Remove 'complete' validation entirely, and let third-party crates perform extra checks.

**Comment by bwasty** [comment]
`gltf::Unvalidated::validate_completely` does include `validate_minimally` now, so I think the API is quite ok. I wouldn't deprecate validation and leave the door open to add more, perhaps more expensive validations over time. The idea to use the crate as a basis for a general purpose validator (C interface?) isn't entirely off the table, is it? (At least I wouldn't close the door for it).

Doing only 'complete' validation might lead to leaving out certain validations if they seem 'expensive'.
Not sure about making it a cargo feature - I imagine a case where you'd want full validation in debug builds and minimal/no validation in release builds. Could this be done with a feature flag? 
Or, a quite specific thing for the viewer maybe, a cli arg to set validation level at runtime (default is 'complete', but if it fails you might wanna ignore that and load anyway.)

**Comment by alteous** [comment]
You raise some very good points here. Especially regarding debug / release behaviour.

I'm thinking let's no deprecate, after all.

**Comment by alteous** [comment]
Decision: Will not deprecate.
