### ISSUE TITLE
Fix clippy issues

### ISSUE THREAD

**Issue by bwasty** [gltf-rs/gltf#111]
`cargo clippy` shows quite a number of issues. I think we should address them for the 1.0 release, either by fixing or [configuring/annotating](https://github.com/rust-lang-nursery/rust-clippy#configuration) them away (clippy is starting to become a bit pedantic sometimes...).

Usage hint:
```
cargo install clippy // requires recent nightly!
cargo clippy --all --features="names"
```

**Comment by alteous** [comment]
Clippy doesn't compile for me on the latest nightly. Could you post your `clippy` lints for the `incoming` branch?

**Comment by bwasty** [comment]
Strange, my nightly is from 2017-09-21 and works fine...
https://gist.github.com/bwasty/21ae877413e4770e4eb5d1b05ebd6284

**Comment by alteous** [comment]
It might be a Mac vs Linux thing.
