### ISSUE TITLE
gltf-utils: problems with PrimitiveIterator::joints_u16 

### ISSUE THREAD

**Issue by bwasty** [gltf-rs/gltf#113]
**First problem**: reaching unreachable code for SmilingFace:
```
     ...
     Running `target/debug/gltf-viewer ../gltf/glTF-Sample-Models/2.0/SmilingFace/glTF/SmilingFace.gltf`
thread 'main' panicked at 'internal error: entered unreachable code', /Users/bwasty/.cargo/registry/src/github.com-1ecc6299db9ec823/gltf-utils-0.9.2/src/lib.rs:396:17
stack backtrace:
   ...
   5: std::panicking::begin_panic
   6: gltf_utils::Joints::new
   7: <gltf::mesh::Primitive<'a> as gltf_utils::PrimitiveIterators<'a>>::joints_u16::{{closure}}
   8: <core::option::Option<T>>::map
   9: <gltf::mesh::Primitive<'a> as gltf_utils::PrimitiveIterators<'a>>::joints_u16
  10: gltf_viewer::render::primitive::Primitive::from_gltf
  11: gltf_viewer::render::mesh::Mesh::from_gltf::{{closure}}
  ...
```

**Second Problem**: `PrimitiveIterator::joints_u16(0, ...)` always returns `None` for the sample models, although the the following do have `JOINTS_0` attributes: BrainStem, CesiumMan, Monster, RiggedFigure, RiggedSimple, WalkingLady.

This is my code: https://github.com/bwasty/gltf-viewer/commit/c38f25aca63689e25c712799e5f7d50ebf64161a.

**Comment by alteous** [comment]
Thanks for reporting. The source of the bug is not obvious. I'll investigate further.
