### ISSUE TITLE
Plans for 1.0.0

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#12]
Now that the implementation of the glTF 1.0 specification is complete, the next steps are to consolidate the library to a production standard. `1.0.0` will be the version where this condition is met.

Below is an non-exhaustive list of things I would expect from a `1.0.0` release:

- [x] Guaranteed backward compatibility for all `1.x.x` releases
- [x] Comprehensive documentation
- [x] glTF 2.0 support
- [x] `KHR_binary_glTF` support
- [x] `Validate` implementations for all 2.0 data structures
- [x] Basic wrapper library for the 2.0 implementation
- [x] ~~Conversion to and from 1.0 / 2.0 assets~~ (see #14)

**Comment by fst3a** [comment]
In my fork I have altered the API a little, changed few bits so that they take generic Read objects instead of Path so that it's possible to load models from memory and such.  Additionally, I don't think that slice calls in v2 are needed.

**Comment by alteous** [comment]
N.B. in the [upcoming wrapper interface](https://github.com/alteous/gltf/blob/wrapper/src/import.rs#L108) we're planning to take generic `Read`.

**Comment by fst3a** [comment]
Oh also I don't think there's a reason to load whole resource in memory and then call from_slice on it.  You could do something like this https://github.com/fst3a/gltf/blob/master/src/v1/gltf.rs#L263

**Comment by alteous** [comment]
> Actual loading of data (images, bins and such) and paths should, in my opinion, be delegated to the user

I mostly agree. The idea behind the `Source` trait is that the user is able to implement their own loader that is called by the importer. This means the importer can make safety guarantees about external data whilst providing a convenient wrapper around the JSON data structures.

Code bloat is a fair concern. Perhaps the library could make the wrapper an opt-out feature.

If all the user wants is to obtain the raw JSON data and validate then that's fine, the appropriate data structures are available in the `json` module.

I like the code snippet, I haven't seen `chain` before. That's a nice trick.

**Comment by fst3a** [comment]
I see.

**Comment by alteous** [comment]
I forgot to mention: The library is moving toward so called 'zero-cost deserialization' of the JSON data structures, which requires `from_slice` or otherwise to obtain the lifetime of the data. The latest code in the `wrapper` branch demonstrates this.

**Comment by alteous** [comment]
In response to @fst3a 's [comment](https://github.com/alteous/gltf/issues/12#issuecomment-309530463), I've added some extra documentation to the [`import`](https://github.com/alteous/gltf/blob/wrapper/src/import.rs#L10-L59) and [`json`](https://github.com/alteous/gltf/blob/wrapper/src/json/mod.rs#L10-L112) modules explaining how the import process may be customised by the user. The relevant `from_reader`, `to_string`, etc. functions from `serde_json` have been [re-exported](https://github.com/alteous/gltf/blob/wrapper/src/json/mod.rs#L161-L178) to hopefully alleviate any version mismatch issues.

**Comment by alteous** [comment]
Once https://github.com/alteous/gltf/issues/34 is closed this issue will enter a 'final discussion phase'.

**Comment by alteous** [comment]
## Final discussion phase

### The next version will be 1.0!

**Comment by alteous** [comment]
Well... looks like the plan to release as 1.0 didn't work out. I anticipate a further minor release (0.11.0) before a 1.0 release. The changes between 0.11 and 1.0 should be minimal.
