### ISSUE TITLE
Glb doesn't load on Big-endian system

### ISSUE THREAD

**Issue by fst3a** [gltf-rs/gltf#120]
Tested on router, apparently it is due transmutes in glb loading code.  Currently working on fix (adds dependency on `byteorder` crate).  I think this is worth considering (aswell as getting rid of as many unsafes as required) before 1.0 release.

**Comment by alteous** [comment]
Yea, it would be, since glTF uses little endian for everything. I think it's fine to target only little endian architectures for 1.0 unless there exists some really common hardware (consoles?) that would require it.

**Comment by fst3a** [comment]
You may be right, i'm pretty there are pretty much no relevant BE machines other than network hardware these days in existence.  I'd still like to put some effort to make the library sound if you don't mind.

**Comment by alteous** [comment]
No problem. I look forward to your PR. :smile:
