### ISSUE TITLE
AccessorIter is unsound can lead to undefined-behavior in safe code

### ISSUE THREAD

**Issue by fst3a** [gltf-rs/gltf#121]
It also will probably not work properly on a BE system, I didn't test, though.

```rust
extern crate gltf;
extern crate gltf_utils;

use gltf_utils::AccessorIter;

use std::{fs, io};

#[derive(Debug)]
pub struct Dummy;

impl gltf_utils::Source for Dummy {
    fn source_buffer(&self, _: &gltf::Buffer) -> &[u8] {
        &[0xff; 1024]
    }
}

fn main() {
    let file = fs::File::open("../tests/minimal_accessor_min_max.gltf").unwrap();
    let mut reader = io::BufReader::new(file);
    let gltf = gltf::Gltf::from_reader(&mut reader).expect("yes")
        .validate_minimally().expect("yes 2");
    let dummy = Dummy;
    let a2 = gltf.accessors().nth(0).unwrap();
    let a12 = gltf.accessors().nth(1).unwrap();

    // With bools
    {
        // UB because a bool that isn't 0 or 1 is invalid in Rust.
        let mut whoops = AccessorIter::<[bool; 2]>::new(a2, &dummy);
        let bools = whoops.next().unwrap();
        println!("{:?}", bools);
        println!("{:?} {:?}",
                 unsafe { *(&bools as *const _ as *const u8) },
                 unsafe { *(&true as *const _ as *const u8) });
    }

    // With refs
    {
        // Twice UB: gets a dummy reference and struct is not repr(C).
        #[derive(Debug, Copy, Clone)]
        #[repr(packed)]
        struct Ref {
            a: &'static u32,
            b: u32,
        }
        let mut whoops = AccessorIter::<Ref>::new(a12, &dummy);
        let refs = whoops.next().unwrap();
        // Oops!
        println!("{:?}", refs);
    }
}
```

**Comment by fst3a** [comment]
Also, in gltf-importer validation strategy can be selected to be skipped which again "safely" does an "unsafe" action (calls unsafe `skip_validation` method).  But I am not sure if this was intended.  If library can function safely even if validation is skipped, perhaps unsafe should be removed from it?

**Comment by alteous** [comment]
>  If library can function safely even if validation is skipped, perhaps unsafe should be removed from the method?

Maybe. The idea is to discourage users from using `skip_validation`, that's why `unsafe` is required! There's nothing *really* unsafe about skipping validation, but the library will panic if the glTF is indeed invalid.

**Comment by alteous** [comment]
To address the OP:

`AccessorIter` is quite unsafe but I'm not sure where to address this. We could mark `AccessorIter::new` unsafe but then it's not really the creation that is unsafe but rather its iteration.

`AccessorIter<'a, T>` should be `AccessorIter<'a, T> where T: Copy` for safety. It's my fault for missing that detail.

**Comment by fst3a** [comment]
It already is `T: Copy`.  And `align_of::<T>() > 4` will not make it safe, as references are 4 bytes long on 32 bit architectures, bools will still fit and C enum default discriminant size is 4 bytes too.  I'll try to figure this out.

**Comment by alteous** [comment]
> And align_of::<T>() > 4 will not make it safe, as references are 4 bytes long on 32 bit architectures, bools will still fit and C enum default discriminant size is 4 bytes too.

I can't imagine a scenario where this would not be safe. The [valid data types](https://docs.rs/gltf/0.9.0/gltf/accessor/enum.DataType.html) require a 4-byte alignment at most, and all glTF buffer data is 4-byte aligned regardless of type (this is checked in the validation stages).

**Comment by fst3a** [comment]
You misunderstood my comment.  First of all this assertion will not catch bools, chars and enums with no payload, which all fit just fine in 4 bytes and the fact that you can put arbitrary values makes it undefined behavior when reading them.  Here is excerpt from [rustonomicon](https://doc.rust-lang.org/nomicon/what-unsafe-does.html): 

All the core language cares about is preventing the following things:
* Producing invalid primitive values:
  * a bool that isn't 0 or 1
  * an undefined enum discriminant
  * a char outside the ranges [0x0, 0xD7FF] and [0xE000, 0x10FFFF]
  * ..
* ..

But you are otherwise correct, if AccessorIter constructor methods and is only used for floats and integers by the library (like it currently is) it will make it not possible to introduce undefined behavior in safe code by user.

**Comment by alteous** [comment]
Oh, I understand what you mean now.

How about we address this by allowing `T` to be a subset of the primitive types Rust provides? This can be achieved with a marker trait.

```rust
pub mod marker {
    /// Better name required!
    pub trait Data {}
    impl Data for i8 {}
    impl Data for u8 {}
    impl Data for i16 {}
    impl Data for u16 {}
    impl Data for i32 {}
    impl Data for u32 {}
    impl Data for f32 {}
    impl<T: Data> Data for [T; 1] {}
    impl<T: Data> Data for [T; 2] {}
    impl<T: Data> Data for [T; 4] {}
    impl<T: Data> Data for [T; 8] {}
    impl<T: Data> Data for [T; 16] {}
    impl<T: Data> Data for [[T; 2]; 2] {}
    impl<T: Data> Data for [[T; 3]; 3] {}
    impl<T: Data> Data for [[T; 4]; 4] {}
}

pub struct AccessorIter<'a, T: marker::Data> { ... }
```

**Comment by fst3a** [comment]
That would work.  You can also change visibility of marker module to be private, rustc should not complain (as seen in bincode crate).  But I believe that we should use approach without transmute magic instead.
