### ISSUE TITLE
Consider getting rid of Error type

### ISSUE THREAD

**Issue by fst3a** [gltf-rs/gltf#126]
The `Error` type is too generic.  `Gltf::from_*` will never return anything other than `Error::Deserialize`, `Glb::from_*` will never return anything other than `Error::Glb` and validation methods will never return anything but `Error::Validation`.

**Comment by alteous** [comment]
There are lots of valid ways of dealing with errors. The current strategy is similar to [`std::io::ErrorKind`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) which covers every possible error in the `io` and `fs` modules.

[`serde_json::Error`](https://docs.rs/serde_json/1.0.3/serde_json/error/struct.Error.html) takes a different approach, implementing the [`serde::ser/de::Error`](https://docs.rs/serde/1.0.12/serde/de/trait.Error.html) trait and writing a wrapper around it for the specific details of (de)serializing JSON.

What do you propose instead? I think it's important for the library to have one consistent error type so the user doesn't have to write all the boilerplate themselves.

**Comment by fst3a** [comment]
I believe that comparison to [std::io::ErrorKind](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) is wrong here.  In case of io and serde, Error types are made to cover all possible implementations of traits (e.g. Read, Serealizer, Deserializer etc), which all return same error type.  In case of gltf, though, there is no trait to implement which would require such generic Error type.  Instead, what we have is that 
constructors of each different type returns only one specific sub-type of Error so generic Error is redundant.

As for boilerplate, I think it is fine to delegate writing Error type which covers every possible Gltf (and extra) errors to the user.  If library does not ever make use for all sub-types/cases of Error in any single method at once, what's the point of having it in the library?  It also might cause extension problems (think that gltf gets some new method like `rebuild_tangents()` which returns its own error type.  It would probably be made into sub-type of Error as well?

**Comment by fst3a** [comment]
I believe that comparison to [std::io::ErrorKind](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) is wrong here.  In case of io and serde, Error types are made to cover all possible implementations of traits (e.g. Read, Serealizer, Deserializer etc), which all return same error type.  In case of gltf, though, there is no trait to implement which would require such generic Error type.  Instead, what we have is that 
constructors of each different type returns only one specific sub-type of Error so generic Error is redundant.

As for boilerplate, I think it is fine to delegate writing Error type which covers every possible Gltf (and extra) errors to the user.  If library does not ever make use for all sub-types/cases of Error in any single method at once, what's the point of having it in the library?  It also might cause extension problems (think that gltf gets some new method like `rebuild_tangents()` which returns its own error type.  It would probably be made into sub-type of Error as well?

**Comment by alteous** [comment]
> As for boilerplate, I think it is fine to delegate writing Error type which covers every possible Gltf (and extra) errors to the user.

I disagree. For the sake of user convenience, the crate should provide a 'catch-all' error type, because the boilerplate code is large and annoying to write. I agree however that functions should return specific error types instead of the generic one.

I suggest we follow this pattern: https://play.rust-lang.org/

**Comment by fst3a** [comment]
Alright, then maybe Error type should at least have a
```rust
#[doc(hidden)]
__Nonexhaustive
```
variant to discourage users from performing exhaustive matches on the generic error?

**Comment by alteous** [comment]
Sounds good to me.

**Comment by alteous** [comment]
I've been experimenting with this idea on my [`error-type`](https://github.com/alteous/gltf/tree/error-type) branch. It's not very ergonomic; I have doubts whether this has significant benefits.

**Comment by fst3a** [comment]
Well, appears to be almost the way I'd expect such to be, except that `Gltf::from_reader` and siblings still appear to return general `Error` instead of specific one of their own.  Mind explaining how these are not ergonomic?  Having specific error types guarantees that when user is, for example, just loading Gltf they will never get a validation error, when otherwise they'd have to put `unreachable!()` in the match arms.  And if user still wants to just catch all of them into "big snowball" they can just add transformer `.map_err(Into::into)`, or if they propagate errors using `?` the `.into()` it is done for them.

**Comment by alteous** [comment]
Actually, I've changed my mind on this. I like your suggestion of removing the generic error type.
