### ISSUE TITLE
Re-license under MIT/Apache 2.0?

### ISSUE THREAD

**Issue by fst3a** [gltf-rs/gltf#132]
To begin with, I'm not personally concerned by what MIT permits (does not conflict with personal use cases) but most Rust OSS projects are commonly licensed this way so maybe we should follow.

As far as I understand, it is to allow more compatibility freedom (MIT permits inclusion in GPL2 projects) but *I am no lawyer*.  Here's a related issue in another project with lengthy explanation: https://github.com/gfx-rs/gfx/issues/847

**Comment by alteous** [comment]
https://github.com/gltf-rs/gltf/blob/master/CONTRIBUTING.md#license-agreement ?

**Comment by fst3a** [comment]
Oh right, i'm blind, sorry
