### ISSUE TITLE
gltf-utils clean up and fast path forwarding

### ISSUE THREAD

**Issue by fst3a** [gltf-rs/gltf#138]
Hello,

so recently gltf-utils' AccessorIter got several fast paths which make methods nth, last and count be O(1) but they were not forwarded in wrapping types (Positions, Normals etc), which are used by the user instead of AccessorIter directly, making fast paths dormant and useless (for now).  Forwarding all fast paths is a problem because of big amount of copy-paste required which will make future maintenance harder etc.  I propose two possible solutions to this:

0. A macro with few rules is used which expands to type definition and Iterator trait implementation
1. Wrapper types wrap contents instead of AccessorIter, that is, we get `pub struct Position(pub [f32; 3])` now and positions method would return `AccessorIter<'a, Position>` instead.

I myself prefer solution 1 over 0.  There is also a similar problem in scene.rs of core crate.

Please write your own suggestion about solving this and/or discuss existing.

**Comment by alteous** [comment]
Positions, normals, and tangents are the simple case. The others (colours, texture coordinates, joints, and weights) are all different. Since the number of cases is low, I'd suggest just duplicating the code for now.

**Comment by alteous** [comment]
Also, one could always just call `nth` etc on the internal iterator type.

```rust
impl Iterator for Positions {
    ...
    fn nth(&mut self, n: usize) -> Option<Self::item> {
        self.0.nth(n)
    }
}

**Comment by fst3a** [comment]
Well, I am talking specifically about what you're showing.  Having to copy paste a lot of code which will forward call to inner iterator.

**Comment by fst3a** [comment]
Nice (in my opinion) alternative (as mentioned in the issue) would be to have public wrapper types for _data_ instead of iterators themselves, e.g.:
```rust
#[derive(Debug, Copy, Clone, PartialEq)] pub struct Position(pub [f32; 3]);
``` 
Creating new such type is not as tedious as new AccessorIter-wrapping type (which will might get worse in case more special *Iterator traits and/or fast paths are implemented), as these only require implementation of small AccessorItem trait.  Then PrimitiveIterators::position method would return AccessorIter<'a, Position>, potentially reducing over a kloc of code we _would_ otherwise have there to even less of what there is now.  In case you are concerned about ergonomics, please don't be, as you can easily desugar them in e.g. function arguments with almost no additional effort.

**Comment by alteous** [comment]
How would this work with colours, texture coordinates, joints, and weights?

**Comment by fst3a** [comment]
I see no problem with colors and and texture coordinates (return an enum just like it is now), as for joints and weights, appropriate transforms could be implemented inside the AccessorItem::from_slice perhaps?

**Comment by fst3a** [comment]
Actually I am not very certain about what would be the best way for the four complex ones you describe, I think I'll experiment a bit and report results.

**Comment by fst3a** [comment]
@alteous what do you think about [this](https://github.com/fst3a/gltf/blob/gltf-utils-reduce/gltf-utils/src/lib.rs)?  This has wrapper types for strong typing for types that can be obtained from accessors and wrapping iterator which produces them, from which you can to get a weaker-typed one.

I'm not sure about what would be the best way to provide iterator casts (e.g. casting WrappingIter<'a, TexCoordU8> to WrappingIter<'a, TexCoordF32>, current approach is pretty asymmetric as it returns TexCoordF32.  What if my UV data is stored as U16?  Casting from e.g. u16 to normalized f32 to u16 is lossy).

Nevertheless, currently, types like TexCoordU8 etc. are castable not only to their directly corresponding primitive array type ([u8; 2] in this case) but also to "biggest" of the group ([f32; 2] in this case).  I'm not sure if it should behave like this, though.  Perhaps alternative would be to provide casts within a group, e.g. TexCoordU8 to TexCoord{U16,F32}; TexCoordU16 to TexCoord{U8, F32} etc?  Or maybe group types like Colors will simply implement Iterator trait several times, for every item type.  That would introduce more code copypaste, though, and their use would get a lot more complicated due to ambiguities.

Additionally, WrappingIter could possibly be removed in favor of using AccessorIter directly.  Or its existence could be justified better by changing it to yield unwrapped type immediately (Wrapping::Inner).

**Comment by fst3a** [comment]
Here is an [alternative](https://github.com/fst3a/gltf/blob/gltf-utils-reduce-alt0/gltf-utils/src/lib.rs) which is simpler and closer to what was before.

**Comment by alteous** [comment]
@fst3a I don't like it at all, sorry. Delegating the conversions between normalized types to the user is a step backwards.

> This has wrapper types for strong typing for types that can be obtained from accessors

What's the benefit of this? It introduces an awful lot of code. The main motivation for the redesign is to avoid lots of (perhaps copy/pasted) code, no?

> What if my UV data is stored as U16? Casting from e.g. u16 to normalized f32 to u16 is lossy).

That's the user's problem, not ours. The idea behind `TexCoordsF32` (and others) is that there's no loss of data and works for every case. Handling all the other cases is beyond the scope of `gltf_utils`.

Ideally, the user would copy glTF buffers directly into GPU buffers and use `Accessor` to determining the vertex layout for each primitive. For example, see the [glTF runtime vertex definition](https://github.com/tomaka/vulkano-examples/blob/gltf/gltf/gltf_system.rs#L687) from `vulkano-examples`.

**Comment by fst3a** [comment]
@alteous
> What's the benefit of this? It introduces an awful lot of code. The main motivation for the redesign is to avoid lots of (perhaps copy/pasted) code, no?

Well, none, admittedly, got carried away a little, which was fixed in alt0 branch.  The main motivation for redesign was to avoid lots of copy-pasted forwarding methods in each Iterator implementation.  I will try to do something with Wrapping trait in alt0 branch to get normalizing casts back.

Also, I am aware about "copy glTF buffers directly into GPU buffers" but in, for example, my use case it's not entirely possible, because in my renderer each model unit has all vertices and indices in one huge buffer, and a slice of index buffer determines which "sub model" to draw, which requires a bit of conversion of some data at loading, so this is the reason I'd _also_ want to have iterators yielding either underlying type directly, without casting, so that the user code would do the casts instead.

**Comment by fst3a** [comment]
Greetings @alteous, I have restarted from incoming branch, giving user ability to unwrap the iterator from result as well as moved casting iterators to separate modules.  It unfortunately did not reduce amount of copy paste, but at least allows user to have more lossy conversions easily (e.g. on Colors, Joints, TexCoords and Weights).  Could you pre-review https://github.com/fst3a/gltf/commit/01d5dd0d736145a645541ed85902d25684902ebc and state your concerns or deny it completely, and then if it is okay it could be filled with docstrings and be made submitted through a PR?

**Comment by alteous** [comment]
At first glance I love it, awesome work!

**Comment by alteous** [comment]
A PR would be appreciated. I'll be able to review in detail tomorrow.

**Comment by fst3a** [comment]
Okay thanks.

**Comment by fst3a** [comment]
https://github.com/gltf-rs/gltf/pull/146
