### ISSUE TITLE
Review newly added ChannelIterators API

### ISSUE THREAD

**Issue by fst3a** [gltf-rs/gltf#141]
I am a bit puzzled by the auxiliary API added recently in https://github.com/gltf-rs/gltf/pull/140/commits/8fb7cebe0dc92c61dc59a63700349ad164c621d7.  Notably, each channel can only ever be of one type "translation", "rotation", "scale" or "weights", which make corresponding getter methods look deceptive, in sense that only one of them ever returns `Some(T)` for certain channel object.  Perhaps these methods could be replaced with a single method returning an `enum` of appropriate `AccessorIter`s?

**Comment by fst3a** [comment]
@Elzair

**Comment by alteous** [comment]
An `enum` return type would be most appropriate.

**Comment by Elzair** [comment]
I just submitted a pull request to fix this. #142
