### ISSUE TITLE
Change metallic_roughness texture to occlusion_roughness_metallic

### ISSUE THREAD

**Issue by SiebenCorgie** [gltf-rs/gltf#147]
Hi,

I am using this crate to load my gltf models. I always followed the docs when it comes to the metallic_roughness texture. However, I found at several places that the way this texture is packed has changed to:

R: Occlusion
G: Roughness
B: Metallic

Places I found this are the [official sample models](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoomBox/glTF/BoomBox_occlusionRoughnessMetallic.png)
and in the blender exporter for the [way you have to pack substance designer materials](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#substance-painter).

I didn't find the part in the specification and the official docs are not helping either (for instance [this](https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/figures/gltfOverview-2.0.0a.png) nice overview picture mentions roughness at green and metallic at blue, but occlusion is in a separate texture).

Any comment, or maybe a change for a new release?

-Siebencorgie

**Comment by alteous** [comment]
Interesting. The specification matches your observation.

From [`material.occlusionTexture`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialocclusiontexture):

> The occlusion map texture. The occlusion values are sampled from the R channel. Higher values indicate areas that should receive full indirect lighting and lower values indicate no indirect lighting. These values are linear. If other channels are present (GBA), they are ignored for occlusion calculations.

From [`pbrMetallicRoughness.metallicRoughnessTexture`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicroughnesstexture):

> The metallic-roughness texture. The metalness values are sampled from the B channel. The roughness values are sampled from the G channel. These values are linear. If other channels are present (R or A), they are ignored for metallic-roughness calculations.

Combining these three channels into one texture makes sense; however, it is not required by the specification.

**Comment by alteous** [comment]
Our documentation is out of date. The [`PbrMetallicRoughness`](https://docs.rs/gltf/0.9.3/gltf/material/struct.PbrMetallicRoughness.html#method.metallic_roughness_texture) docs are misleading:

> The first component (R) contains the metallic-ness of the material. The second component (G) contains the roughness of the material. If the third component (B) and/or the fourth component (A) are present then they are ignored.

The docs for `OcclusionTexture` have no information.

Thanks for spotting this!

**Comment by SiebenCorgie** [comment]
No problem.

I don't know if another release is planed, but I guess it would be good to update the docs since they are apart from that accurate. 

Btw. thanks for the great crate!

**Comment by alteous** [comment]
There is a 0.10 release planned although it is overdue by an embarrassingly long time.

> Btw. thanks for the great crate!

My pleasure!
