### ISSUE TITLE
name() function

### ISSUE THREAD

**Issue by hodasemi** [gltf-rs/gltf#158]
Hi, 

I would like to access the name of an animation. 
Is it possible to add a `fn name(&self) -> Option<String>` function to types where the name is already imported? 
I saw that name is a member of the gltf_json animation, but I can't access it since it is private.

EDIT: Ok, nvm. I just saw it in the source code. It doesnt appear in the doc, that should be fixed to reduce confusion.

**Comment by alteous** [comment]
Hi, you need to enable the `names` feature. See the README for instructions. I agree this could be better documented.

**Comment by alteous** [comment]
In the next version we will expose `names` as a default feature.
