### ISSUE TITLE
Incompatibility with the spec: Glb::to_write serializes Nones as nulls

### ISSUE THREAD

**Issue by wlinna** [gltf-rs/gltf#173]
`Glb::to_write` serializes `None`s as nulls. This is problematic, because gltf specification does not allow `null` values. If a property is set to `None`, it should be omitted.

For example, in the case of `accessors`, the spec doesn't require defining `sparse`, but when it is defined, `null` values are NOT allowed.

Because of this, `GLTFLoader` of ThreeJS throws when I try to use a GLB file serialized by `gltf-rs/gltf`.

Here's a reference to the spec:

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/accessor.sparse.schema.json

As you can see, `type `is set to `"object"`, not `["object", "null"]`

**Comment by alteous** [comment]
This is quite interesting as I had assumed the [roundtrip_binary_gltf test](https://github.com/gltf-rs/gltf/blob/master/tests/roundtrip_binary_gltf.rs#L60) would have caught this. I imagine this will be an easy fix in gltf-json.

**Comment by wlinna** [comment]
In fact, I've already fixed it locally, but I'll leave the PR for tomorrow
