### ISSUE TITLE
Support for custom extensions

### ISSUE THREAD

**Issue by Ralith** [gltf-rs/gltf#180]
The current design seems to be such that extensions must have support hardcoded into gltf-json to be usable. This represents a barrier to use of new, experimental, and vendor-specific extensions, some of which may not even be appropriate for general inclusion. Are there any plans to support use of extensions that the library doesn't have specific knowledge of?

**Comment by alteous** [comment]
The question is how. The only idea I have is to return `serde_json::Value` for extensions gltf-json doesn't support. Does this seem reasonable?

**Comment by alteous** [comment]
If https://github.com/serde-rs/json/issues/355 is ever implemented then it would be possible to 'lazily-deserialized' custom extensions.

**Comment by Ralith** [comment]
> Does this seem reasonable?

That seems like the obvious approach to me, yeah.

**Comment by alteous** [comment]
Great news! https://github.com/serde-rs/json/pull/480 exists.

**Comment by alteous** [comment]
Closed in favour of #231.
