### ISSUE TITLE
Export (GltfBuilder)

### ISSUE THREAD

**Issue by anderejd** [gltf-rs/gltf#187]
I am going to do some sort of gltf export in the near future and I would like it to be based on this library. Is export functionality on the road map? Would a PR be welcome?

I found this (part of a) comment in another thread:

> Being about to export glTF would be a great future feature. I'm considering a builder struct GltfBuilder where we could make guarantees of the validity of references the users provides, but personally I'd rather concentrate on just loading at the moment.

**Comment by alteous** [comment]
The builder idea is not on the 1.0 roadmap. Pull requests are always welcome.

The crate supports exporting binary glTF and serialising the JSON for standard glTF.

**Comment by alteous** [comment]
I should mention: There is no specific 1.0 roadmap but I am keen to release a version 1.0 shortly as the API is stable. Extensions are the last thing to be addressed.

**Comment by anderejd** [comment]
Thanks for the reply!

> The builder idea is not on the 1.0 roadmap. Pull requests are always welcome.

I might look at that tomorrow. At this point the only thing I need is geometry export for some initial tests. If this is too much work to implement in this crate my fallback plan is to simply use the triangle sample model file as a template and modify the needed parts to export my data instead.

> The crate supports exporting binary glTF and serialising the JSON for standard glTF.

I searched for "export" in the docs and the code and didn't find anything. I also looked for builders and constructors, for example on Mesh the constructor is internal: https://docs.rs/gltf/0.11.2/src/gltf/mesh/mod.rs.html#134 That made me think that the entire in-memory structure is meant to be read-only after it has been created by calling the import functions. What I need is to build the gltf document in-memory, and then serialize it to a file.

Can you give an example of how one can use this crate to build the gltf document in-memory and then export it? What am I missing?

**Comment by alteous** [comment]
> the entire in-memory structure is meant to be read-only after it has been created by calling the import functions

This is correct.  The `Document` struct is the deserialised form of the glTF JSON. Almost all other structs are wrappers around `Document` enabling you to traverse the scene hierarchy easily.

There is no nice way of building/exporting glTF at the moment; however, you are free to call `Document::{from_json, into_json}` and to manipulate the JSON as you wish. The builder idea aims to do exactly this but in a friendly way.

Side note: the `gltf-json` is considered an implementation detail and is inherently unstable.

**Comment by anderejd** [comment]
> Side note: the gltf-json is considered an implementation detail and is inherently unstable.

After a quick look at the gltf-json crate, it seems like what I'm after, thanks!

I'll try the `gltf-json` crate and try to serialize the structures provided by that crate in order to avoid building the json string "by hand".

**Comment by alteous** [comment]
@anderejd : How did you get on with your exporter? Did using `gltf-json` directly address your needs? I'm interested to know what kind of features will be useful for a generic glTF exporter besides builders for the JSON data structures.

**Comment by anderejd** [comment]
My exporter is roughly in the same shape as the example in #193. I do have plans to continue the development of that project but I'm unsure when I'll find the time.

> Did using gltf-json directly address your needs?

Yes, with builders it's a fine base for an exporter.

> I'm interested to know what kind of features will be useful for a generic glTF exporter besides builders for the JSON data structures.

Something to help with generating correct binary buffers of all possible variations would be nice. I did begin that work in #193 as well. My main goal with that initial export PR was to efficiently export simple, but high resolution triangle meshes and to provide an initial exporter implementation to build more advanced features upon.

**Comment by alteous** [comment]
I have an idea:

```rust
struct Member {
    pub offset: usize,
    pub size: usize,
}

trait Vertex {
    fn position() -> Option<Member> {
        None
    }

    fn normal() -> Option<Member> {
        None
    }

    fn tex_coord(_n: u32) -> Option<Member> {
        None
    }

    // etc.

    fn stride() -> usize {
        0
    }
}

#[derive(GltfVertex)]
#[repr(C)]
struct Vertex {
    #[gltf(POSITION)]
    position: [f32; 3],
    #[gltf(NORMAL)]
    normal: [f32; 3],
}

// Generates...
trait Vertex {
    fn position() -> Option<Member> {
        Some(Member { offset: 0, size: 12 })
    }

    fn normal() -> Option<Member> {
        Some(Member { offset: 12, size: 24 })
    }

    fn stride() -> usize {
        24
    }
}
```
This could be used to generate accessors and primitives easily.

**Comment by anderejd** [comment]
Looks nice for simple exporters. I would prefer to avoid compile time code generation for this since that wouldn't work for arbitrary import-process-export scenarios where the gltf binary layout is unknown at compile time.
