### ISSUE TITLE
_allow_unknown_fields should not be serialized?

### ISSUE THREAD

**Issue by anderejd** [gltf-rs/gltf#188]
While experimenting with serialization I found this in the output:
```
      "extras": {
        "_allow_unknown_fields": null
      },
```
It looks like the intent is to not produce any output:

https://github.com/gltf-rs/gltf/blob/4f73f6be7005a09e44235e0a449545715927fcd2/gltf-json/src/extras.rs#L16

**Comment by anderejd** [comment]
The unexpected `"_allow_unknown_fields": null` goes away when enabling the `extras` feature.

**Comment by alteous** [comment]
Well spotted! This is clearly a bug. Will fix in the next release.

**Comment by zpgaal** [comment]
Is there any update on this issue ?

**Comment by alteous** [comment]
Not yet.

**Comment by alteous** [comment]
I believe this is fixed now.
