### ISSUE TITLE
Remove validate_completely

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#195]
This isn't working out for various reasons:

1. One has to call `validate_minimally` before `validate_completely`... so the `completely` suffix is terribly misleading!
2. We hardly ever use it and I don't anticipate any PRs improving its scope anytime soon.
3. The idea of complete validation does not seem to a popular nor in demand feature.
4. For optimal performance applications are not expected to use this feature at run time at all.
5. It introduces perhaps unnecessary code bloat and maintenance overhead.

For these reasons I suggest we abandon `validate_completely`. Furthermore, I suggest also we introduce a lean version of `validate` that doesn't compute the error path if validation fails. With these suggestions I imagine the `Validate` trait to look something like this:

```rust
pub trait Validate {
    /// Validates the invariants required by the library that serde is unable to
    /// check during deserialization.
    ///
    /// Does not report the error source/path if validation errors are found.
    fn validate<R>(&self, _root: &Root, _report: &mut R)
    where
        R: FnMut(Error),
    {
        // nop
    }

    /// Validates the invariants required by the library that serde is unable to
    /// check during deserialization.
    ///
    /// Reports the error source/path if validation errors are found.
    fn validate_verbose<P, R>(&self, _root: &Root, _path: P, _report: &mut R)
    where
        R: FnMut(&Fn() -> Path, Error),
    {
        // nop
    }
}
```

**Comment by anderejd** [comment]
> It introduces perhaps unnecessary code bloat and maintenance overhead.

👍 Reducing complexity is often a good idea, IMHO.

On that note, it doesn't even need to be a trait, simple public function(s) would be useful too.

**Comment by alteous** [comment]
It needs to be a trait for code generation from `gltf-derive` to work.
