### ISSUE TITLE
Replace cgmath by nalgebra through feature flags

### ISSUE THREAD

**Issue by ldesgoui** [gltf-rs/gltf#197]
Hello,

From what I gathered, gltf uses cgmath for pure operations over Vectors/Matrices/Quaternions (in scene::Transform);
It'd be nice to have an optional dependency on cgmath for those who are using nalgebra in their projects instead
I can try starting a PR if this is something you'd be willing to merge

Thanks

**Comment by alteous** [comment]
Hi,

I'm not 100% sure what you're asking for. The crate does indeed use cgmath internally for some conversions but this is merely an implementation detail.

**Comment by ldesgoui** [comment]
Hello,

gltf is the only crate in my project that depends on cgmath, since its use could be replaced by any other maths library, I consider it to be an optional dependency, I'm offering to work on a PR that would make it an actual optional dependency with a similar nalgebra implementation

Thanks

**Comment by bwasty** [comment]
Would be fine for me (optional dependency + nalgebra implementation).

**Comment by repi** [comment]
We would like this as well, tried to get rid of our last dependencies on cgmath
