### ISSUE TITLE
Publish gltf-json 0.12 to crates.io

### ISSUE THREAD

**Issue by anderejd** [gltf-rs/gltf#202]
Hi, I would like to request a new release of gltf-json since the master branch has some changes I depend on. Thanks!

**Comment by bwasty** [comment]
@alteous what do you think?
If you don't have the time you could also add me as an owner on crates.io (or create a GitHub team for that)

**Comment by alteous** [comment]
Makes sense, let's publish.

**Comment by anderejd** [comment]
Thanks! 🎉
