### ISSUE TITLE
[Question] build on Android & iOS

### ISSUE THREAD

**Issue by nvcken** [gltf-rs/gltf#203]
Does it support on Android & iOS

**Comment by bwasty** [comment]
I'm not aware of anyone having tested it, but fundamentally it _should_ work (perhaps with minor adjustments).

**Comment by repi** [comment]
We compile and build this crate on iOS without any issues

**Comment by alteous** [comment]
I take @repi's word for it that the crate builds and works on Android and iOS as expected. We should add these software platforms to our automated testing somehow.
