### ISSUE TITLE
Index<T> is not copy for Non-Copy T

### ISSUE THREAD

**Issue by Veykril** [gltf-rs/gltf#208]
I just noticed that you have to clone Indices manually instead of being able to rely on implicit copying for almost if not all gltf objects due to how derives work for `Copy` and `Clone` and almost all objects not being `Copy` due to their fields. 
https://github.com/gltf-rs/gltf/blob/33197d6231c900ffcef5f196bfa1e258dcc0c310/gltf-json/src/root.rs#L20-L21

Is there a specific reason for this or was this just overlooked? To my understanding an `Index` doesnt own the `T` anyways, so there shouldn't be an issue with implementing those two traits manually for all `T` instead, and changing the `PhantomData<T>` to `PhantomData<*const T>` to hint the compiler that it is not owned by the struct. The latter part would require to manually implement `Send` and `Sync` for `Index<T>` as well though since it still is actually thread-safe.

**Comment by alteous** [comment]
> Is there a specific reason for this or was this just overlooked?

Likely overlooked. Previous versions of Rust may have disallowed `Copy` for `PhantomData` but I can't remember.

**Comment by alteous** [comment]
Fixed in #209.
