### ISSUE TITLE
Validate matrices to be decomposable to TRS

### ISSUE THREAD

**Issue by bwasty** [gltf-rs/gltf#21]
From the 2.0 draft spec:
> Matrices must be decomposable to TRS. This implies that transformation matrices cannot skew or shear.

([Source](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#transformations))

I think it would be good to check the matrices on load. Perhaps this could be optional, so it can be skipped e.g. on release builds.
Relevent discussion on the spec repo: https://github.com/KhronosGroup/glTF/issues/892

**Comment by alteous** [comment]
Good idea. I'm not sure how this could be implemented though.

**Comment by alteous** [comment]
What first comes to mind is transforming the vertices of a simple solid like a tetrahedron and computing the change in the edge lengths. If any scaling takes place then all sides should be scaled by the same amount or else there would be some shear or skew taking place.

**Comment by bwasty** [comment]
There are formulas to extract rotation/translation/scale/skew/shear from matrices:
https://math.stackexchange.com/questions/237369/given-this-transformation-matrix-how-do-i-decompose-it-into-translation-rotati
http://stackoverflow.com/questions/5107134/find-the-rotation-and-skew-of-a-matrix-transformation
http://stackoverflow.com/questions/15420693/how-to-get-rotation-translation-shear-from-a-3x3-homography-matrix-in-c-sharp

My first idea was to extract T/R/S, then re-multiply and assert they're the same. But I'm not sure that's enough to be certain. Second idea: extract only skew and shear and assert that they are not present. Also not entirely sure that's enough.

**Comment by alteous** [comment]
I'm not sure if there's been any consensus or further discussion on this issue. The specification doesn't seem to put any restrictions on the node transform matrices.

**Comment by bwasty** [comment]
I still see it in the spec, just slightly reworded:

> When `matrix` is defined, it must be decomposable to TRS. This implies that transformation matrices cannot skew or shear.

([src](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#transformations))

**Comment by alteous** [comment]
I think the validation may be as simple as checking the bottom row for non-zero values in the matrix. For example this matrix would be acceptable:

```
[ s r r t ][ x ]
[ r s r t ][ y ]
[ r r s t ][ z ]
[ 0 0 0 w ][ 1 ]
```

But this matrix would not:

```
[ s r r t ][ x ]
[ r s r t ][ y ]
[ r r s t ][ z ]
[ 1 2 3 w ][ 1 ]
```

(N.B. row-major example and column-major implementation)

**Comment by bwasty** [comment]
Just saw a comment in the glTF gitter channel that the official validator has this check now -> [isTrsDecomposable](https://github.com/KhronosGroup/glTF-Validator/blob/794d8d8ed5ffab23948b8f5883690c23626f8a81/lib/src/utils.dart#L657-L672).
((speaking of gitter - how about reviving the channel? Might help adoption of the library.))

**Comment by alteous** [comment]
Excellent, thanks for the link.

> speaking of gitter - how about reviving the channel?

Yes, let's do that!

**Comment by alteous** [comment]
Check out the new README. :)

**Comment by bwasty** [comment]
Another hint: the `decompose` function used by the mentioned `isTrsDecomposable` can be found here: https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/matrix4.dart#L1766-L1804

**Comment by scurest** [comment]
A matrix is a TRS matrix if and only if

1. the last row is [0 0 0 1]
2. the columns of its upper-left 3x3 subblock are non-zero and pairwise orthogonal.

The only if direction is just direct computation. The if direction is from  
![trs](https://user-images.githubusercontent.com/11024420/29751969-cd7d8faa-8b1a-11e7-8b9d-36185d966a0a.png)  
By (2), the middle matrix is orthogonal and the ± is chosen to make it have determinant +1 so that it is a rotation.

**Comment by alteous** [comment]
@scurest Thanks!
