### ISSUE TITLE
Publish a new 0.11.4 release on crates.io?

### ISSUE THREAD

**Issue by repi** [gltf-rs/gltf#213]
There has been 2 months since the last 0.11.3 release and a bunch of good improvements and PRs that have been merged in, possible to publish an 0.11.4 release on crates.io?

We currently patch in the git repo to get multiple fixes, but would like to go back to just depend on latest on crates.io instead. 

Thanks!

**Comment by alteous** [comment]
Published as 0.12.

**Comment by repi** [comment]
Thanks!
