### ISSUE TITLE
Release process/schedule

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#216]
Releasing a new version of the crate is somewhat of a chore since a lot of things have to happen at once:

1. Crate numbers must be bumped.
2. Changelog and README/documentation must be updated.
3. All crates need to be tested.
4. All crates need to be published in a certain order: `gltf-derive`, followed by `gltf-json`, followed by the main `gltf` crate.

Naturally this means I'm reluctant to release new versions of the crate! Left unchecked this has caused multiple delays for contributors and I apologise for this. I'm creating this issue in an effort to make the process and release schedule less painful for everybody.

I propose a regular fortnightly or monthly release, providing of course there is something new to release. The current release process could be refined, although I feel these steps are necessary to keep history and dependencies sane. I've considered merging `gltf-json` and `gltf` several times. This has its own upsides and downsides but it would at least take one stage out of the release process.

**Comment by bwasty** [comment]
I would propose to writing all the steps into a .md file at the root of the repo and creating a GitHub team to be added as [`cargo owner`](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner), so you're not the only one who can release.

Simplifying the whole process would be nice, but I think the above could already be enough.
