### ISSUE TITLE
Import buffer data separately from other import data.

### ISSUE THREAD

**Issue by thorjelly** [gltf-rs/gltf#222]
Not sure how to import buffer data alone, because the import module is private, so the function `import_buffer_data` appears inaccessible. It appears that I only have access to opening the gltf file, which doesn't import buffer data, or calling `gltf::import`, which imports both the buffer data and the image data. I already load images on my own, for various reasons, but importing buffer data is useful. Perhaps I am missing something?

**Comment by alteous** [comment]
You're correct: there is no way of loading just buffer data. I never expected this to be a use case.

What kind of API were you expecting? Bear in mind `import_buffer_data` takes a `blob` parameter in order to handle the optional payload in binary glTF.

**Comment by thorjelly** [comment]
I really just mean I don't want to import image data, but I do want to import buffer data and the document. I don't think just importing buffer data without the document would be useful; sorry if the title was misleading.

I want to import images on my own for several reasons. I need to make sure the image data is created with the proper format (it seems to import them with R8G8B8 while I need R8G8B8A8), and that I also process it according to exactly what texture field the image is associated with, whether the texture should be srgb or uniform. There are basically a lot of different ways to import image data and I'm not sure how to get gltf to import them correctly for me. And I already have my own image import routines written which work for my use case, since I need to import images/textures separately from any gltf file anyway.

Just having access to `import_buffer_data` would be fine. It is okay that it takes `blob` because I need to open the document anyway, and can get `blob` from `Gltf::open`. In fact, right now I pretty much just copy/pasted the `import_buffer_data` function and associated functions and it works fine. But it'd be much nicer to use it in the library.

Thanks.

**Comment by Jasper-Bekkers** [comment]
I've had a similar use-case actually to @thorjelly, and I ended up copying out a bunch of the import code just to be able to load images through stb (similar use-case actually, I wanted the data R8G8B8A8 but I also wanted a much smaller compile time dependency). 

Getting `Scheme` and `import_gltf_buffer_data` as `pub` would already help a lot here.

**Comment by experiment9123** [comment]
am I reading this right, that gltf-rs will import the images itself ?  I am trying to get this to work on emscripten and I definitely need it to leave the image loading to me.  In my own custom file format importers, I pass lambdas to deal with texture-loading (eg Fn(pathname)->Tx Tx= user supplied custom texture typeparameter.    
I am trying to use this with a streaming engine, e.g. "load geometry first, load textures asynchronously later"

**Comment by digama0** [comment]
I also ran into this issue. I am translating between two formats that only need to refer to the image without loading it (the input and output both only need to maintain the name of the texture, even if the file is not available at that location when the translator is running), so importing image data is both a waste of time and also causes IO failures. Please make `import_buffer_data` public. For more targeted importing I think it would also make sense to have a function on `buffer::Source` which reads the data for that buffer.
