### ISSUE TITLE
Empty extras are serialized

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#230]
Example

```json
{
    "extras": {}
}
```

We don't need these to be serialized.

**Comment by digama0** [comment]
Bumping this issue since I was about to report it. The problem is that the extras are marked
```rust
    #[cfg_attr(feature = "extras", serde(skip_serializing_if = "Option::is_none"))]
    pub extras: Extras,
```
but since extras are in fact
```rust
/// Data type of the `extras` attribute on all glTF objects.
#[cfg(feature = "extras")]
pub type Extras = Option<::std::boxed::Box<RawValue>>;

/// Data type of the `extras` attribute on all glTF objects.
#[cfg(not(feature = "extras"))]
pub type Extras = Void;
```
they are not an `Option` when the `extras` field is disabled. Suggested fix: `#[cfg_attr(not(feature = "extras"), serde(skip_serializing))]`
