### ISSUE TITLE
Documentation shows only default features

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#233]
The documentation automatically hosted on [docs.rs](https://docs.rs/gltf/) exposes only the default features. We should figure out how to enable them all or else consider hosting the documentation elsewhere.

**Comment by bwasty** [comment]
According to https://docs.rs/about, something like this may work:
```
[package.metadata.docs.rs]
all-features = true
```

**Comment by alteous** [comment]
Sweet, I'll give it a try.
