### ISSUE TITLE
Missing tags for recent versions

### ISSUE THREAD

**Issue by aloucks** [gltf-rs/gltf#237]
The last tag was `0.9.1`.

**Comment by alteous** [comment]
Are these tags useful to anybody?

**Comment by aloucks** [comment]
It's frustrating (in general) to have a dependency on something and not be able easily find the code that represents the version that you're using. I guess you could argue that crates.io makes a copy of the source, but I would think it's best practice to tag that commit in source control as well. 

Digging out the commits for the missing tags might not be worth it, but it would be nice if things were tagged moving forward.

I can't even remember the specific thing I was looking for now, but I wanted to see a diff between releases and noticed there were no recent tags. I think this will become more important if/when you switch to generating most of the code (i.e. #234).

**Comment by alteous** [comment]
> It's frustrating (in general) to have a dependency on something and not be able easily find the code that represents the version that you're using.

I'm glad you pointed this out. I agree with you having faced the same issue for other projects. I understand the necessity now.

For the sake of consistency and completeness I've dug through the commit history to tag releases appropriately. The commit history is a bit [muddled](https://github.com/gltf-rs/gltf/commit/6c372688adc8f168aaac6a7b4a9fac21831f5025#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) but using the crates.io release dates and the change log commit history I can figure it out.

Going forward I need to be more careful in regards to commit history and release dates and numbers in future.

**Comment by alteous** [comment]
We now have tags for the following revisions:
```sh
$ git tag
0.10.0
0.10.1
0.11.1
0.11.2
0.11.3
0.12.0
0.6.0
0.6.1
0.7.0
0.8.6
0.9.0
0.9.1
0.9.2
0.9.3
```
I don't think releases before 0.9.3 are worth considering.
