### ISSUE TITLE
CubicSpline has same documentation as CatmullRomSpline

### ISSUE THREAD

**Issue by rukai** [gltf-rs/gltf#259]
Looks like the CubicSpline documentation was copy pasted from the CatmullRomSpline documentation and then not corrected.
https://docs.rs/gltf/0.14.0/gltf/animation/enum.Interpolation.html

I looked up in the specs to see what it was supposed to be, but it doesn't exist??? So I'm a little confused, if it should actually exist at all.
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0

**Comment by alteous** [comment]
Oops, well spotted! Catmull-Rom splines were removed by https://github.com/KhronosGroup/glTF/pull/1171 back in December 2017. I kept it around in case somebody was depending on it but now that seems an unlikely scenario. I suggest we remove it entirely.
