### ISSUE TITLE
buffer_view should be optional in sparse accessors

### ISSUE THREAD

**Issue by elrnv** [gltf-rs/gltf#266]
It seems like it could be useful to be able to omit the initial values in sparse accessors:

> A sparse accessor differs from a regular one in that bufferView property isn't required. When it's omitted, the sparse accessor is initialized as an array of zeros of size (size of the accessor element) * (accessor.count) bytes.
(taken from https://github.com/KhronosGroup/glTF/tree/master/specification/2.0)

I'm not sure how big of a change it would be to make buffer_view an Option<Index> though.

**Comment by alteous** [comment]
This is a good point. I worked on this recently and didn't notice that section. I don't think there are any sample models that omit this `bufferView` entry so we would need to make a new model to test this case.

**Comment by elrnv** [comment]
For some more context, the example I had in mind was a keyframed animation sequence with a morph target per keyframe. In this scenario the weights are animated and it is conceivable that all default weights are set to zero. In this case, each keyframe (except first) would correspond to a set of weights with a 1.0 for the target to be used at the keyframe and zero for all other targets. Here the size of the initial weights buffer view will be (# keyframes) * (# targets), which has all entries set to zero and a sparse accessor with a 1.0 for each keyframe (so # keyframes of 1.0s). For an example of 1000 keyframes ( and say ~1000 morph targets), the number of allocated zeros is size_of::<f32>() * 1000 * 1000 = 3.8MB. This is independent of mesh size so it could potentially be a significant chunk.

I'm running into this scenario for a soft tissue simulation sequence, where every vertex is animated programmatically. I think this kind of use case can be pretty common.

A simple test case like this could be a cube with a single morph target with two keyframes. I don't currently know of any means of creating gltf samples like this other than programmatically, but I guess it can be done with a tweak to this library :P.

I don't currently have time to tackle this, but I may get to it eventually.

**Comment by Delamare2112** [comment]
Just to note, currently the latest Adobe Dimension (build 3aa2998b3d3d63f4d10229f55f1891303b66b8c1), when exporting to web, generates a gltf file which uses sparse accessors without buffer views.  The example gltf-tree cannot deserialize these files for this reason.

**Comment by dakom** [comment]
Btw it is also mentioned in the [properties reference](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessor) (e.g. that bufferView is optional)
