### ISSUE TITLE
accessor offset should return 0 if not set

### ISSUE THREAD

**Issue by dakom** [gltf-rs/gltf#268]
Here is how buffer view offset() looks:

```
pub fn offset(&self) -> usize {
    self.json.byte_offset.unwrap_or(0) as usize
}
```

Here is accessor offset():

```
pub fn offset(&self) -> usize {
    self.json.byte_offset as usize
}
```

Should the accessor `offset()` not also be `unwrap_or(0)` ?

**Comment by alteous** [comment]
No, the current code is correct. The latter is [marked `#[serde(default)]`](https://github.com/gltf-rs/gltf/blob/master/gltf-json/src/accessor.rs#L198) so it will be zeroed if not set. Arguably these ought to be consistent though.
