### ISSUE TITLE
scene::iter::Nodes and scene::iter::Children are O(n^2)

### ISSUE THREAD

**Issue by Jasper-Bekkers** [gltf-rs/gltf#284]
Because their `next` implementation calls `.nth(..)` these operations are running in `O(n^2)` time and have been showing up in my profiles pretty considerably on large-ish gltf files.

A simple fix would seem to be to `collect()` the document nodes into a `Vec` first, and then index into that instead.

```
    fn next(&mut self) -> Option<Self::Item> {
        self.iter
            .next()
            .map(|index| self.document.nodes().nth(index.value()).unwrap())
    }
```

**Comment by aloucks** [comment]
I've submitted a fix for this here: https://github.com/gltf-rs/gltf/pull/282

**Comment by Jasper-Bekkers** [comment]
That's great timing! The speedup is also pretty amazing with that.

Before:
```
Loading names took 6.2612ms
Loading meshes took 22.0554527s
Loading instances took 15.0084255s
Loading transforms took 12.9378781s
Loading animations took 1.6904ms
Loading lights took 7µs
Loading textures took 600ns
Finalizing scene load took 514.7µs
```

After:
```
Loading names took 5.535ms
Loading meshes took 8.9622108s
Loading instances took 16.6748ms
Loading transforms took 14.2661ms
Loading animations took 1.2115ms
Loading lights took 6.2µs
Loading textures took 500ns
Finalizing scene load took 1.265ms
```

**Comment by aloucks** [comment]
@Jasper-Bekkers I've pushed another commit to implement `nth` for the remaining iterators. I suspect that you're not hitting the quadratic behavior on these ones unless you're calling `nth` yourself, but I'm still curious if you notice any difference. Could you re-run your benchmark?

**Comment by Jasper-Bekkers** [comment]
Just ran those tests and the results for those changes are in the noise.

```
Loading names took 5.247ms
Loading meshes took 3.4383576s
Loading instances took 16.9769ms
Loading transforms took 14.8652ms
Loading animations took 1.8099ms
Loading lights took 500ns
Loading textures took 300ns
Finalizing scene load took 909µs
```

"Loading meshes" was optimized by other means, the rest is more or less the same as before.

**Comment by aloucks** [comment]
@Jasper-Bekkers Cool - that's pretty much what I expected. The change to the primary iterators makes a huge difference but there probably isn't anything in your code calling `th` on the other ones.

**Comment by Jasper-Bekkers** [comment]
This can be closed now that the PR has landed.
