### ISSUE TITLE
How to load an image

### ISSUE THREAD

**Issue by Roba1993** [gltf-rs/gltf#287]
Hi guys,

I try to use gltd to load a model to render with wgpu.
My problem is, that I can't find a way to get the image data, when it's part of the .gltf file.
I probably miss some base things here?

**Comment by alteous** [comment]
What does your import code look like? The typical usage for web /wgpu is:

```rust
let (document, buffers, images) = gltf::import_slice(&your_gltf)?;
let your_image_data = &images[n].data;
```

**Comment by Roba1993** [comment]
Okay got it... Stupid me.
The gltf:::open() function is really only for inspectiong the file not to really load something.

Thank you for the help!
