### ISSUE TITLE
[question] how do i get a skin's inverse bind matrix?

### ISSUE THREAD

**Issue by torresguilherme** [gltf-rs/gltf#295]
I'm trying to import a skinned model and I can't figure out how to get the inverse bind matrix value. I'm trying to get it as a vec so I can use it for a nalgebra Matrix4. 

This is how I'm currently trying:

` 
    let mut accessor_max: Matrix4<f32> = Matrix4::default();

    let mut accessor_min: Matrix4<f32> = Matrix4::default();

    let inverse_bind_option = skin.inverse_bind_matrices();

    match inverse_bind_option {

        Some(accessor) => {

            accessor_max = match accessor.max() {

                Some(value) => {

                    // ???

                }

            }

        },

        None => ()

    };`

Every time I try to get the **value** I fall into an infinite loop of matches.

**Comment by aloucks** [comment]
Here's an example:

```rust
for skin in import.doc.skins() {
    let name = skin.name().map(|name| name.into());
    let joint_node_indices: Vec<usize> = skin.joints().map(|j| j.index()).collect();
    for node_index in joint_node_indices.iter().cloned() {
        nodes[node_index].is_joint = true;
    }
    let reader = skin.reader(|buffer| Some(&import.buffers[buffer.index()]));
    let inverse_bind_matrices = if let Some(inverse_bind_matrices) = reader.read_inverse_bind_matrices() {
        inverse_bind_matrices.collect()
    } else {
        let identity = *mat4(&cgmath::Matrix4::identity());
        vec![identity; joint_node_indices.len()]
    };

    println!(" Loaded {} joints for skin: {:?}", joint_node_indices.len(), name);

    assert_eq!(joint_node_indices.len(), inverse_bind_matrices.len());

    skins.push(Skin {
        joint_node_indices,
        inverse_bind_matrices,
        name,
    })
}
```

**Comment by torresguilherme** [comment]
@aloucks thank you!
