### ISSUE TITLE
Support for KHR_materials_variants

### ISSUE THREAD

**Issue by james7132** [gltf-rs/gltf#301]
Support for the `KHR_materials_variants` extension would be super useful for packing multiple GLTF files with only material differences instead of needing to ship all items while duplicating meshes, nodes, and animations.

Full docs for the extension: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_variants

**Comment by alteous** [comment]
This looks interesting! I imagine it wouldn't be difficult to add data structures for this.

**Comment by alteous** [comment]
Implemented by https://github.com/gltf-rs/gltf/pull/319.
