### ISSUE TITLE
Return impl Iterator instead of structs

### ISSUE THREAD

**Issue by Yamakaky** [gltf-rs/gltf#309]
For example:
- `Animation::channels(&self) -> Channels<'a>` -> `Animation::channels(&self) -> impl Iterator<Item=Channel<'a>>`
- `Scene::nodes(&self) -> Nodes<'a>` -> `Scene::nodes(&self) -> impl ExactSizeIterator<Item=Node<'a>> `

It is easier to read the doc with this change, you can directly click from `Animation` to `Channel` without passing by the boilerplate `Nodes` and getting the `Item` definition in the `impl Iterator`.

I `cargo test`ed these two changes, I can do the others if you are ok with this change. `gltf::iter` would then be a private module.

**Comment by a1phyr** [comment]
Note that `rustdoc` includes a small helper to show important traits implementations, such as `Iterator`, `Read` or `Write`.

![image](https://user-images.githubusercontent.com/47725341/143504501-47f845ae-e5e1-4d6a-a816-ed5f60d6dcbf.png)

**Comment by alteous** [comment]
Note: the structs are named this way in accordance to the [API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#iterator-type-names-match-the-methods-that-produce-them-c-iter-ty).

**Comment by Yamakaky** [comment]
On the other hand, the [return impl Trait rfc](https://github.com/rust-lang/rfcs/blob/master/text/1522-conservative-impl-trait.md) explicitly uses `impl Iterator` as example. I assume this guideline was written before the feature was available.
