### ISSUE TITLE
Don't panic on any malformed glTF input

### ISSUE THREAD

**Issue by repi** [gltf-rs/gltf#359]
This is a rather broad issue, but it would be wonderful if this crate could get to the point where there can be no internal panics regardless of what input data is passed in, only returned `Result`s with errors to the user of the library.

## Use cases

Our use case is our application where users pass in large amounts of arbitrary glTF data and we do not want any accidentally or intentionally malformed glTF files (json or binaries) to cause a panic the application when parsing/loading it.
We currently do capture panics from the `gltf` crate which helps to suppress it but it is not ideal as still have a Rust panic hook that displays the panic (can't change that as it is a global property).

## Tracking

- [x] #298
- [x] https://github.com/gltf-rs/gltf/pull/358

**Comment by alteous** [comment]
It looks like this has been fixed now. Please re-open otherwise.
