### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by hw762** [gltf-rs/gltf#366]
It has gone quite a while without any new releases, despite seemingly getting quite a few patches. Is this project still being maintained? Or I'll have to migrate to something else.

**Comment by Looky1173** [comment]
I have the same concern – it would be great to hear from a maintainer of this crate.

AFAIK, there aren't any alternatives to this crate that match its features. All the other crates seem incomplete...

**Comment by alteous** [comment]
It is sporadically maintained.
