### ISSUE TITLE
image data formats

### ISSUE THREAD

**Issue by stefnotch** [gltf-rs/gltf#371]
When one has an [image data struct](https://docs.rs/gltf/1.1.0/gltf/image/struct.Data.html) with a format like `Format::R8G8B8`, how should the bytes be interpreted?

Are they *linear* values between 0 and 255, or are they sRGB values between 0 and 255.

I'm asking, since the source code indicates that [DynamicImage](https://docs.rs/image/latest/image/enum.DynamicImage.html) from the `image` crate is being used
https://github.com/gltf-rs/gltf/blob/69caa857827f534f3f5deade83b37f5b407d79d0/src/image.rs#L146
which defines [RgbImage](https://docs.rs/image/latest/image/type.RgbImage.html), which *might* be in sRGB space https://docs.rs/image/latest/image/struct.Rgb.html ?

**Comment by alteous** [comment]
Hi, good question! It seems no conversion is performed by the [PNG decoder](https://docs.rs/image/latest/src/image/codecs/png.rs.html#248), so it is unspecified. The [glTF spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#images) says:

> Any colorspace information (such as ICC profiles, intents, gamma values, etc.) from PNG or JPEG images MUST be ignored. Effective transfer function (encoding) is defined by a glTF object that refers to the image (in most cases it’s a texture that is used by a material).

So my understanding is the colour space is defined/implied elsewhere, such as the [metallic-roughness material](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#metallic-roughness-material).

> The base color texture MUST contain 8-bit values encoded with the [sRGB opto-electronic transfer function](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#srgb) so RGB values MUST be decoded to real linear values before they are used for any computations. To achieve correct filtering, the transfer function SHOULD be decoded before performing linear interpolation.

> The textures for metalness and roughness properties are packed together in a single texture called metallicRoughnessTexture. Its green channel contains roughness values and its blue channel contains metalness values. This texture MUST be encoded with linear transfer function and MAY use more than 8 bits per channel.

Is this helpful?
