### ISSUE TITLE
Panics on reading a large GLTF due to the .bin being more than ~4GB and `byteLength` using a u32

### ISSUE THREAD

**Issue by Elabajaba** [gltf-rs/gltf#393]
`byteLength` is internally a u32, but that violates the spec which says there's no hard limit on the size of a buffer, though assets should limit themselves to 2^53 to avoid issues with some json decoders.

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#buffers-and-buffer-views-overview

```json
	"buffers": [
		{
			"uri": "redacted.bin",
			"byteLength": 17646210956
		}
	],
```

**Comment by alteous** [comment]
That's interesting. It's good to know there are assets large enough to encounter these kind of issues.

This is a known problem for binary glTF because there is a hard limit on the binary chunk size. For standard glTF with a separate binary payload, you're right to say there is no such limitation. I'll mark this is a bug.

**Comment by ShaddyDC** [comment]
Would a fix to this involve anything beyond changing the types of `Buffer::byte_length` and `View::byte_length` from `u32` to `usize`? The binary buffer size limitation and type should still be enforced through `Header::length` etc, so it shouldn't weaken any guarantees, I don't think. If that's it, I might make a PR for it tomorrow.

**Comment by alteous** [comment]
> Would a fix to this involve anything beyond changing the types of `Buffer::byte_length` and `View::byte_length` from `u32` to ~`usize`~`u64`? The binary buffer size limitation and type should still be enforced through `Header::length` etc, so it shouldn't weaken any guarantees, I don't think. If that's it, I might make a PR for it tomorrow.

I don't think so. I agree it should be `u64` rather than `usize`.
