### ISSUE TITLE
Is there anyway to use gltf in constants?

### ISSUE THREAD

**Issue by coolcatcoder** [gltf-rs/gltf#405]
Not sure if this is the right place to ask, but is there anyway to read/load/open gltf in a constant function?

**Comment by alteous** [comment]
I'm struggling to think of a reason why one might want to do such a thing. Could you provide a motivating example?

**Comment by coolcatcoder** [comment]
I cannot provide a motivating example. However I can provide an example lol. What I would wish to do is create a const array of vertices, and a const array of indices, for use with vulkan. Sure I could manually create these by hand, but it would be easier to grab them from gltf in a const function.

**Comment by kpreid** [comment]
You could use `gltf` from inside a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) of your package, which can run whatever kind of non-const calculation it wants, and then generate Rust code containing constant arrays (either with simple string formatting, or [`uneval`](https://docs.rs/uneval)).

**Comment by coolcatcoder** [comment]
Ooh that sounds good, thanks for the info!
