### ISSUE TITLE
bug: Reader::read_positions does not honour `accessor.componentType`

### ISSUE THREAD

**Issue by kanerogers** [gltf-rs/gltf#416]
Hi there!

## Background
When attempting to import a node whose position accessor has type 5123 (`UNSIGNED_SHORT`), the following debug assertion is tripped on line 348 of `src/accessor/util.rs`:

```rust
debug_assert_eq!(mem::size_of::<T>(), accessor.size())
```

Since `T = ReadPositions::Item` is `[f32; 3]` and `accessor.size()` is 6, this resolves to

```rust
debug_assert_eq!(mem::size_of::<[f32; 3]>(), accessor.size()) // left == right failed: left: 12, right: 6
```

However, this is incorrect. It is perfectly valid (though admittedly uncommon) for a position accessor to be of any type other than `UNSIGNED_INT` as per [section 5.1.3](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_accessor_componenttype) of the spec. I have confirmed the file can be validated and opened with Gestaltor.

I have attached below a zip file containing a `glb` that reproduces the above issue. A similar file can be obtained by running [gltfpack](https://meshoptimizer.org/gltf/) over any glTF file without including the `-noq` (disable quantisation) option.

This issue was first raised in #311 but was incorrectly self-closed as user error.

## Solution
The solution is to handle `read_positions` in a similar fashion to `read_colors`; finding the correct data type for the accessor and delegating to a specific reader.

[enderman.zip](https://github.com/gltf-rs/gltf/files/14784585/enderman.zip)

**Comment by alteous** [comment]
Thanks for reporting, I'll look into it.

**Comment by alteous** [comment]
This is the same issue as https://github.com/gltf-rs/gltf/issues/400.

> It is perfectly valid (though admittedly uncommon) for a position accessor to be of any type other than UNSIGNED_INT as per [section 5.1.3](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_accessor_componenttype) of the spec.

This is not true. There is a list of valid accessor and component types for each semantic value. For `POSITION`, this is limited to `VEC3` of `float` in the base specification.

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes-overview

This list is expanded by the [`KHR_mesh_quantization`](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md#extending-mesh-attributes) extension, but this is not supported currently.

**Comment by kanerogers** [comment]
Aha, right you are - I had not read that part of the spec previously, and hadn't taken note of the presence of the mesh quantization extension!

Thanks so much for the concise and informative response.
