### ISSUE TITLE
Mint integration

### ISSUE THREAD

**Issue by vitvakatu** [gltf-rs/gltf#67]
Tracking progress of [`mint`](https://github.com/kvark/mint) integration.

**Comment by alteous** [comment]
If it's not too much trouble, could this be made an opt-out cargo feature? That is, the feature is enabled by default but the user can remove it if version mismatch issues crop up.

**Comment by vitvakatu** [comment]
Sure, I'll try to do it. It almost done by the way, I just need to revise it to make sure I didn't forget anything.

**Comment by alteous** [comment]
Great! I look forward to seeing your PR.

**Comment by bwasty** [comment]
@vitvakatu any news on this?

**Comment by vitvakatu** [comment]
Oh, I got distracted by other stuff. If someone can do that - it would be great. I hope I can find some time in a week or so, though

**Comment by alteous** [comment]
Continuing here: https://github.com/gltf-rs/gltf/tree/mint-support

**Comment by alteous** [comment]
How about `euler` support? :stuck_out_tongue:

**Comment by alteous** [comment]
Is there anything else left to be implemented?

**Comment by alteous** [comment]
Closing since I'm unconvinced of the benefit of this. Please complain otherwise.

**Comment by kvark** [comment]
I just started using this crate, and I could see how `mint` helps here.
Consider this code:
```rust
```
