### ISSUE TITLE
Idea: Generic child object iterator

### ISSUE THREAD

**Issue by alteous** [gltf-rs/gltf#97]
@udoprog suggested [a generic approach](https://github.com/udoprog/gltf/blob/master/src/child_iter.rs) on Gitter for iterating over child objects of glTF objects, which is an interesting idea.

```rust
use std::slice;

/// Iterator over parented slices.
#[derive(Clone, Debug)]
pub struct ChildIter<'a, T: ChildBuilder<'a>> {
    /// The parent struct.
    parent: T::Parent,

    /// The internal iterator.
    iter: slice::Iter<'a, T::Json>,
}

impl<'a, T: 'a + ChildBuilder<'a>> ChildIter<'a, T> {
    pub fn new(parent: T::Parent, iter: slice::Iter<'a, T::Json>) -> ChildIter<'a, T> {
        ChildIter {
            parent: parent,
            iter: iter,
        }
    }
}

impl<'a, T: 'a> Iterator for ChildIter<'a, T>
where
    T: ChildBuilder<'a>,
{
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        self.iter.next().map(
            |json| T::new(self.parent.clone(), json),
        )
    }
}

pub trait ChildBuilder<'a> {
    type Parent: 'a + Clone;
    type Json: 'a;

    fn new(Self::Parent, &'a Self::Json) -> Self;
}
```

My gut tells me this might not be good idea, but I would like to discuss futher.

Main advantages of a generic iterator:

* Better documentation of iterator item type.
* Avoid code duplication code (although this could also be achieved with a macro).
* Reducing number of 'fixed' names post 1.0 release.

Points of contention are:

* Lifetimes may have to be bound to the parent similar to #85.
* Inconsistent return types (e.g. a tuple would be needed for `Primitive::Attributes`).
* Rust API guidelines suggest iterator types should match their method names.

**Comment by bwasty** [comment]
I don't have a strong opinion on this, but it doesn't seem to bring enough benefits to justify 'violating' the API guidelines ([this one](https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-iter-ty), right?).

**Comment by alteous** [comment]
Yes, that's the guideline I was referring to.

Code duplication is becoming a problem. The `ExactSizeIterator` issues could have been avoided if I had used macros or otherwise. I'm not keen on the idea of macros because it's harder to reason about the code. An extreme example would be [assimp-rs](https://github.com/Eljay/assimp-rs/blob/master/src/import/structs.rs), where almost everything is implemented by a macro - I want to avoid this as much as possible.

**Comment by alteous** [comment]
Perhaps we could have a hybrid approach...

```rust
macro_rules! iterator {
    ($wrapper_iterator:ty, $generic_iterator:ty) => {
        struct $wrapper($generic);
        impl Iterator for $wrapper {
            type Item = $generic::Item;
            fn next(&mut self) -> Option<Self::Item> {
                self.0.next()
            }
        }
    };
}

iterator!(Children, Node);

impl Node {
    fn children(&self) -> Children {
        Children(Iter::new(...))
    }
}
```
