### ISSUE TITLE
Transform::decomposed is wrong for matrices with negative determinant

### ISSUE THREAD

**Issue by scurest** [gltf-rs/gltf#99]
Eg. for `Transform::Matrix { matrix: Matrix4::from_nonuniform_scale(1.0, 1.0, -1.0) })`, it currently produces a rotation of [0, 0, 0, √2] and a scale of [1, 1, 1].

One way to fix it is to negate one of the columns and the corresponding scaling factor, pushing the reflection from the rotation part to the scaling part. Something like

    if m.determinant() < 0 {
        m[0] = -m[0];
        sx = -sx;
    }

Note that there are at least four choices for how to do this: negate the first column, negate the second column, negate the third column, negate all the columns. Because of this, and the fact that the map from quaternions to matrices is a double cover, I think the docs for `decomposed` should say "Returns _a_ decomposed representation...".

**Comment by alteous** [comment]
@scurest Thanks for reporting! Will fix ASAP.
